# Generated by Django 3.1.1 on 2020-09-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200926_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
